### ISSUE TITLE
Bei einem Error, lässt sich nicht erkennen woran es gelegen hat

### ISSUE THREAD

**Issue by dergel** [omphteliba/ff_gpt_tools#1]

**Comment by dergel** [comment]
Ich bekomme in meinem Fall nur die Info, dass ein Error 1 aufgetaucht ist. Wäre cool, wenn man sehen könnte, was das genaue Problem ist.

**Comment by omphteliba** [comment]
@dergel schau mal, ob das eine Lösung ist: Ich schreibe, den log Text in die Datenbank.

**Comment by dergel** [comment]
Sorry. Nachricht ist untergegangen. Ja das passt so, vielen dank.

**Comment by dergel** [comment]
Da ich das lokal teste, kommt nichts raus, weil die URL von ChatGPT nicht erreichbar ist. So interpretiere ich mal die Meldung:

`Error: No content to summarize for Article ID: 13.`

**Comment by omphteliba** [comment]
> Da ich das lokal teste, kommt nichts raus, weil die URL von ChatGPT nicht erreichbar ist. So interpretiere ich mal die Meldung:
> 
> `Error: No content to summarize for Article ID: 13.`

Nein, das ist nach dem Bereinigen des Artikels nichts übrig geblieben, was man an ChatGPT senden kann. Aber ich seh grade, dass ich dafür yrewrite nutze. Muss ich noch ändern...
