### ISSUE TITLE
Cronjob wird bei "Re-Installation" immer wieder neu erstellt

### ISSUE THREAD

**Issue by dpf-dd** [omphteliba/ff_gpt_tools#3]
Mir ist noch aufgefallen, dass ein Re-Install des AddOns immer und immer wieder den zugehörigen Cronjob "ff_gpt_tools_cronjob" anlegt. Ich vermute aber, dass der Cronjob nur exakt 1x existieren soll - da fehlt also bei der Installation eine Abfrage, ob der zu installierende Cronjob bereits vorhanden ist. Ist dies der Fall, dann nicht nochmal installieren...!?

**Comment by omphteliba** [comment]
Stimmt, muss ich noch abfragen!

**Comment by omphteliba** [comment]
Fixed
