### ISSUE TITLE
Metafeld wie med_description muss vorhanden sein!

### ISSUE THREAD

**Issue by VIEWSION** [omphteliba/ff_gpt_tools#6]
Ich hab's auch mal ausprobiert. Der Ansatz ist echt vielversprechend. Leider ging beim ersten Test mein Frontend nicht mehr... und das lag an dem fehlenden med_description. Das ist nicht automatisch gegeben - aber das Aden geht davon aus. Das sollte man vorher abfragen...

**Comment by omphteliba** [comment]
Ok, jetzt wird abgefangen, wenn es das Image Description Meta Feld in der rex_media Datenbank nicht gibt.
